//ADMIN:update password
PATCH http://localhost:8080/api/user/settings/password
Content-Type: application/json
authorization: {{token}}


{
  "oldPassword":"2017214271",
  "newPassword":"xiongxi159",
  "confirmNewPassword": "xiongxi159"
}

###
//ADMIN:delete tutor
DELETE http://localhost:8080/api/admin/tutor/2
Accept: application/json
authorization: {{token}}


###
//ADMIN:add student
POST http://localhost:8080/api/admin/student
Content-Type: application/json
authorization: {{token}}

{
  "number": 20170001,
  "name": "Qtrer"
}

###
//ADMIN:add tutor
POST http://localhost:8080/api/admin/tutor
Content-Type: application/json
authorization: {{token}}

{
  "number": 201701,
  "name": "BO"
}

###
//ADMIN:login
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "name": "Laner",
  "number": 2017224492,
  "password": "laner"
}

> {% client.global.set("token", response.headers.valueOf("authorization")); %}

###
